import { CircleDollarSign, Info, RefreshCw, Scale, SunMedium, UtilityPole } from "lucide-react";
import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { getLiveStatus } from "../api";
import { useAsync } from "../hooks";
import { ErrorState, LoadingState } from "../ui/State";

function formatUpdatedAt(value) {
  return new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(value));
}

export function LiveDashboard() {
  const { data, error, loading } = useAsync(getLiveStatus, []);

  if (loading) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? "Live data unavailable"} />;

  const cards = [
    {
      title: "Grid Draw",
      value: data.grid_draw_kw,
      note: "Power being drawn from the grid",
      icon: UtilityPole,
      colorClass: "blue",
    },
    {
      title: "Solar Generation",
      value: data.solar_generation_kw,
      note: "Power being generated by solar",
      icon: SunMedium,
      colorClass: "green",
    },
    {
      title: "Net Usage",
      value: data.net_usage_kw,
      note: "Negative means export to grid",
      icon: Scale,
      colorClass: "purple",
    },
    {
      title: "Savings Today",
      value: 1.35,
      note: "vs. yesterday",
      icon: CircleDollarSign,
      colorClass: "green",
      prefix: "$",
      unit: "",
    },
  ];

  return (
    <section className="live-dashboard">
      <header className="live-header">
        <div>
          <h1>Live Dashboard</h1>
          <p>Real-time overview of your energy usage and solar generation.</p>
        </div>
        
      </header>

      <div className="live-card-grid">
        {cards.map(({ title, value, note, icon: Icon, colorClass, prefix, unit }) => (
          <article className="live-stat-card" key={title}>
            <div className={`live-icon ${colorClass}`}>
              <Icon size={34} />
            </div>
            <div>
              <h2 className={colorClass}>{title}</h2>
              <div className="live-value">
                <strong>{prefix ?? ""}{value.toFixed(prefix ? 2 : 1)}</strong>
                <span>{unit ?? "kW"}</span>
              </div>
              <p>{note}</p>
            </div>
          </article>
        ))}
      </div>

      <div className="live-chart-grid">
        <article className="live-chart-card">
          <div className="live-graph-image solar-image" role="img" aria-label="Solar panels on a home roof">
            <img
              src="/images/solar1.webp"
              alt="Solar panels installed on a home roof"
              onError={(event) => {
                event.currentTarget.hidden = true;
              }}
            />
          </div>
          <div className="chart-title-row">
            <h2 className="green">Solar Generation Over Time</h2>
            <Info size={17} />
          </div>
          <ResponsiveContainer width="100%" height={320}>
            <LineChart data={data.live_series} margin={{ top: 18, right: 20, left: 8, bottom: 14 }}>
              <CartesianGrid stroke="#d8dde6" strokeDasharray="4 4" vertical={false} />
              <XAxis dataKey="label" tickLine={false} axisLine={{ stroke: "#d8dde6" }} />
              <YAxis
                domain={[0, 6]}
                tickLine={false}
                axisLine={{ stroke: "#d8dde6" }}
                label={{
                  value: "Solar Power (kW)",
                  angle: -90,
                  position: "insideLeft",
                  fill: "#168000",
                  fontWeight: 700,
                }}
              />
              <Tooltip formatter={(value) => [`${value} kW`, "Solar Power"]} />
              <Legend verticalAlign="top" align="left" iconType="plainline" />
              <Line
                type="monotone"
                dataKey="solar_kw"
                name="Solar Power (kW)"
                stroke="#8ac000"
                strokeWidth={3}
                dot={{ r: 5, strokeWidth: 2, fill: "#8ac000" }}
                activeDot={{ r: 7 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </article>

        <article className="live-chart-card">
          <div className="live-graph-image grid-image" role="img" aria-label="Electrical transformer and grid lines">
            <img
              src="/images/grid.jpg"
              alt="Electrical transformer connected to grid lines"
              onError={(event) => {
                event.currentTarget.hidden = true;
              }}
            />
          </div>
          <div className="chart-title-row">
            <h2 className="blue">Grid Usage Over Time</h2>
            <Info size={17} />
          </div>
          <ResponsiveContainer width="100%" height={320}>
            <LineChart data={data.live_series} margin={{ top: 18, right: 20, left: 8, bottom: 14 }}>
              <CartesianGrid stroke="#d8dde6" strokeDasharray="4 4" vertical={false} />
              <XAxis dataKey="label" tickLine={false} axisLine={{ stroke: "#d8dde6" }} />
              <YAxis
                domain={[0, 6]}
                tickLine={false}
                axisLine={{ stroke: "#d8dde6" }}
                label={{
                  value: "Power from Grid (kW)",
                  angle: -90,
                  position: "insideLeft",
                  fill: "#0b5fd3",
                  fontWeight: 700,
                }}
              />
              <Tooltip formatter={(value) => [`${value} kW`, "Power from Grid"]} />
              <Legend verticalAlign="top" align="left" iconType="plainline" />
              <Line
                type="monotone"
                dataKey="grid_kw"
                name="Power from Grid (kW)"
                stroke="#0b5fd3"
                strokeWidth={3}
                dot={{ r: 5, strokeWidth: 2, fill: "#0b5fd3" }}
                activeDot={{ r: 7 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </article>
      </div>

      <p className="live-footnote">
        <Info size={17} />
        <span>All values are in kilowatts (kW). Data updates every 30 seconds.</span>
      </p>
    </section>
  );
}
